[project]
name = 'stackstay'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.stackstay-badge]
path = 'contracts/stackstay-badge.clar'
clarity_version = 3
epoch = 'latest'

[contracts.stackstay-dispute]
path = 'contracts/stackstay-dispute.clar'
clarity_version = 3
epoch = '3.2'

[contracts.stackstay-escrow]
path = 'contracts/stackstay-escrow.clar'
clarity_version = 3
epoch = '3.2'

[contracts.stackstay-reputation]
path = 'contracts/stackstay-reputation.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
